{{- if (gt (int .Values.replicaCount) 1) }}
{{- if .Capabilities.APIVersions.Has "policy/v1/PodDisruptionBudget" }}
apiVersion: policy/v1
{{- else }}
apiVersion: policy/v1beta1
{{- end }}
kind: PodDisruptionBudget
metadata:
  name: {{ template "kube-operator.fullname" . }}
  labels: {{ include "kube-operator.labels" . | nindent 4 }}
spec:
{{- include "podDisruptionBudget.spec" . | indent 2 }}
  selector:
    matchLabels:
      {{- include "kube-operator.selectorLabels" . | nindent 6 }}
{{- end }}
