variables:
  SUITES_IMAGE: jashbook/datatestsuites:latest
  TAGS_NAME: "aws-test"
  SOURCE_TYPE: ""
  DEFAULT_TYPE: ""


default:
  before_script:
    - echo "$CI_PIPELINE_SOURCE"
    - echo "$CI_COMMIT_REF_NAME"
    - echo "$GITLAB_USER_ID"


workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH'
      variables:
        SOURCE_TYPE: "DEFAULT"
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      variables:
        SOURCE_TYPE: "MR"
    - when: always


stages:
  - build
  - test
  - merge-request
  - deploy
  - deploy-default


build-push:
  stage: build
  image: $SUITES_IMAGE
  tags:
    - "$GITLAB_USER_ID"
  rules:
    - if: '$SOURCE_TYPE == "MR" || $SOURCE_TYPE == "DEFAULT"'
      when: never
    - when: always
  script:
    - echo "1"
    - echo "make mod-vendor"
    - echo "make lint"
    - echo "make"

test-push:
  stage: test
  image: $SUITES_IMAGE
  tags:
    - "$GITLAB_USER_ID"
  rules:
    - if: '$SOURCE_TYPE == "MR" || $SOURCE_TYPE == "DEFAULT"'
      when: never
    - when: always
  script:
    - echo "2"
    - echo "make test"


build-mr:
  stage: build
  image: $SUITES_IMAGE
  tags:
    - "$TAGS_NAME"
  rules:
    - if: '$SOURCE_TYPE == "MR" || $SOURCE_TYPE == "DEFAULT"'
      when: always
  script:
    - echo "1"
    - echo "make mod-vendor"
    - echo "make lint"
    - echo "make"

test-mr:
  stage: test
  image: $SUITES_IMAGE
  tags:
    - "$TAGS_NAME"
  rules:
    - if: '$SOURCE_TYPE == "MR" || $SOURCE_TYPE == "DEFAULT"'
      when: always
  script:
    - echo "2"
    - echo "make test"


test-mr-2:
  stage: merge-request
  image: $SUITES_IMAGE
  tags:
    - "$TAGS_NAME"
  rules:
    - if: '$SOURCE_TYPE == "MR" || $SOURCE_TYPE == "DEFAULT"'
      when: always
  script:
    - echo "3"
    - echo "make test"


deploy:
  stage: deploy
  image: $SUITES_IMAGE
  tags:
    - "$TAGS_NAME"
  rules:
    - if: '$DEFAULT_TYPE == "DEFAULT"'
      when: always
  script:
    - echo "4"
    - echo "helm install"

deploy-default:
  stage: deploy-default
  image: $SUITES_IMAGE
  tags:
    - "$TAGS_NAME"
  rules:
    - if: '$DEFAULT_TYPE == "DEFAULT"'
      when: always
  script:
    - echo "5"
    - echo "helm test"







