# permissions for end users to edit databaseinstances.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: databaseinstance-editor-role
rules:
- apiGroups:
  - dac.infracreate.com
  resources:
  - databaseinstances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dac.infracreate.com
  resources:
  - databaseinstances/status
  verbs:
  - get
