name: Move assigned card
on:
  issues:
    types:
      - assigned
  push:
    branches: [ "hzs-test-template" ]
  pull_request:
    branches: [ "hzs-test-template" ]

jobs:
  move-assigned-card:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@5bcba1c1c091a222584d10913e5c060d32c44044
        with:
          project: hzs-test
          column: Todo
          repo-token: "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"