name: CICD-PULL-REQUEST-CHECK

on:
  pull_request_review:
    types: [submitted]


jobs:
  check-trigger:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - name: check trigger
        run:
          exit 0

  trigger-pr:
    needs: check-trigger
    if: ${{ github.event.review.state == 'approved' && needs.check-trigger.result == 'success' }}
    uses: ./.github/workflows/cicd-pull-request.yml
    secrets: inherit
