name: CI-TEST

on:
  push:
    branches: [ "hzs-test-template" ]

  workflow_dispatch:

jobs:
  make-build:
    runs-on: [self-hosted,Linux,ARM64]
    container: jashbook/datatestsuites:latest
    steps:
      - uses: actions/checkout@v3
      - name: make build
        run: |
          make mod-vendor
          make lint
          make
  make-test:
    runs-on: [ self-hosted,Linux,ARM64 ]
    container: jashbook/datatestsuites:latest
    needs: [make-build]
    steps:
      - uses: actions/checkout@v3
      - name: make test
        run: |
          make mod-vendor
          make test