name: CICD-PULL-REQUEST

on:
  pull_request:

jobs:
  pr-test:
    runs-on: [ self-hosted, aws-ec2-k8s-runner ]
    steps:
      - uses: actions/checkout@v3
      - name: helm test
        run: |
          make helm-test