name: CICD-PULL-REQUEST

on:
  push:
    branches:
      - '*'
      - '*/*'
    tags-ignore:
      - '*'

jobs:
  init:
    runs-on: ubuntu-latest
    outputs:
      cn-account: ${{ steps.cn-account.outputs.cn-account }}
    steps:
      - name: Init
        id: cn-account
        run: |
          CN_ACCOUNT="Root user for with password: root && xhsjyd\nEncrypted password for:"
          echo "1$CN_ACCOUNT"
          CN_ACCOUNT=${CN_ACCOUNT#*"Root user for with password: "}
          CN_ACCOUNT=${CN_ACCOUNT%"Encrypted password for:"*}
          echo "2$CN_ACCOUNT"
          CN_ACCOUNT=${CN_ACCOUNT%"\\"*}
          echo "3$CN_ACCOUNT"
          echo 'cn-account='"$CN_ACCOUNT" >> $GITHUB_OUTPUT

  deploy:
    runs-on: ubuntu-latest
    needs: init
    steps:
      - name: Deploy
        run: |
          echo "${{ needs.init-gm.outputs.cn-account }}"

  deploy-2:
    runs-on: ubuntu-latest
    needs: [ init,deploy ]
    steps:
      - name: Deploy
        run: |
          echo "${{ needs.init-gm.outputs.cn-account }}"


 
