name: CICD-MERGE

on:
  pull_request:
    types:
      - closed

env:
  GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}


jobs:
  minikube-test:
    if: ${{ github.event.pull_request.merged == true &&  github.base_ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    name: make test in minikube
    steps:
      - uses: actions/checkout@v3
      - name: setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19'

      - name: setup minikube
        run: |
          sed -i "s/--cpus=4/--cpus=2/" ./Makefile
          make minikube-start

      - name: checkout testinfra
        uses: actions/checkout@v3
        with:
          repository: linghan-hub/testinfra
          path: testinfra
          token: ${{ env.GITHUB_TOKEN }}

      - name: run test
        run: |
          cd testinfra
          make test