name: CICD-MERGE

on:
  pull_request:
    types:
      - closed
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
  GO_VERSION: '1.19'
  TEST_TAG: test


jobs:
  minikube-test:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    name: make test in minikube
    steps:
      - uses: actions/checkout@v3
      - name: setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: setup minikube
        run: |
          make minikube-start

      - name: checkout testinfra
        uses: actions/checkout@v3
        with:
          repository: linghan-hub/testinfra
          path: testinfra
          token: ${{ env.GITHUB_TOKEN }}

      - name: run test
        run: |
          cd testinfra
          make test