name: CICD-MERGE

on:
  pull_request:
    types:
      - closed

jobs:
  merge-test:
    if: github.event.pull_request.merged == true
    runs-on: [ self-hosted, aws-ec2-k8s-runner ]
    steps:
      - uses: actions/checkout@v3
      - name: helm test
        run: |
          make helm-test