name: CICD-PULL-REQUEST

on:
  pull_request:


jobs:
  trigger-mode:
    name: make test
    runs-on: ubuntu-latest
    outputs:
      trigger-mode: ${{ steps.get_trigger_mode.outputs.trigger_mode }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Get trigger mode
        id: get_trigger_mode
        run: |
          TRIGGER_MODE=`bash .github/utils/utils.sh --type 6`
          echo $TRIGGER_MODE
          echo trigger_mode=$TRIGGER_MODE >> $GITHUB_OUTPUT

  make-test:
    needs: trigger-mode
    if: contains(needs.trigger-mode.outputs.trigger-mode, '[test]')
    runs-on: ubuntu-latest
    steps:
      - name: make test
        run: echo ${{ needs.trigger-mode.outputs.trigger-mode }}

  check-image:
    needs: trigger-mode
    if: needs.trigger-mode.outputs.trigger-mode == '[docker]'
    runs-on: ubuntu-latest
    steps:
      - name: check image
        run: echo ${{ needs.trigger-mode.outputs.trigger-mode }}

  check-helm:
    needs: trigger-mode
    if: needs.trigger-mode.outputs.trigger-mode == '[deploy]'
    runs-on: ubuntu-latest
    steps:
      - name: check helm
        run: echo ${{ needs.trigger-mode.outputs.trigger-mode }}
