name: CICD-PUSH

on:
  workflow_dispatch:
    inputs:
      params:
        description: 'params'
        required: false
        default: ''
  push:
    branches:
      - '*'
      - '*/*'
    tags-ignore:
      - '*'

jobs:
  script:
    runs-on: ubuntu-latest
    steps:
      - name : docs
        if: ${{ inputs.params == *'docs'* }}
        shell: bash
        run: |
          echo "${{ inputs.params }}"
      - name : github
        if: ${{ inputs.params == *'.github'* }}
        shell: bash
        run: |
          echo "${{ inputs.params }}"
      - name : docker
        if: ${{ inputs.params == *'docker'* }}
        shell: bash
        run: |
          echo "${{ inputs.params }}"
      - name : all
        if: ${{ inputs.params == *'all'* }}
        shell: bash
        run: |
          echo "${{ inputs.params }}"
#          cr --help
#          go version
#          TAG_NAME="v0.14.1"
#          echo "${TAG_NAME/v/}"
#          CHAR_PATH="deploy/helm"
#          echo "${CHAR_PATH%/*}"
#          brew install skopeo
#          skopeo sync -h
          


#  script:
#    runs-on: ubuntu-latest
#    container: apecloud/terraform-aws-cli:latest
#    steps:
#      - name: download runner latest
#        run: |
#          apt-get update
#          apt-get install -y -qq groff
#          aws ec2 delete-key-pair help


#  make-build:
#    if: startsWith(github.event.head_commit.message, 'Merge pull request') != true
#    runs-on: [ self-hosted, aws-ec2-k8s-runner ]
#    steps:
#      - uses: actions/checkout@v3
#      - name: make build
#        run: |
#          make mod-vendor
#          make lint
#          make
#  make-test:
#    if: startsWith(github.event.head_commit.message, 'Merge pull request') != true
#    runs-on: [ self-hosted, aws-ec2-k8s-runner ]
#    needs: [make-build]
#    steps:
#      - uses: actions/checkout@v3
#      - name: make test
#        run: |
#          make test
#      - name: upload cover result
#        uses: actions/upload-artifact@v3
#        with:
#          name: cover_result
#          path: cover.html
#  helm-test:
#    if: startsWith(github.event.head_commit.message, 'Merge pull request') != true
#    runs-on: [ self-hosted, aws-ec2-k8s-runner ]
#    needs: [ make-test ]
#    steps:
#      - uses: actions/checkout@v3
#      - name: helm test
#        run: |
#          make helm-test
