name: CICD-TEST

on: [push, pull_request]

jobs:
  make-build:
    runs-on: [self-hosted,local-k8s-runner]
    if: ${{ github.event_name == 'push' }}
    steps:
      - uses: actions/checkout@v3
      - name: make build
        run: |
          make mod-vendor
          make lint
          make
  make-test:
    runs-on: [ self-hosted,local-k8s-runner ]
    if: ${{ github.event_name == 'push' }}
    needs: [make-build]
    steps:
      - uses: actions/checkout@v3
      - name: make test
        run: |
          make mod-vendor
          make test
  helm-test:
    runs-on: [ self-hosted,local-k8s-runner ]
    if: ${{ github.event_name == 'push' }}
    needs: [ make-test ]
    steps:
      - uses: actions/checkout@v3
      - name: helm test
        if: ${{ !env.ACT }}
        run: |
          make helm-test
      - name: helm test local
        if: ${{ env.ACT }}
        run: |
          make helm-test-local


  make-build-pr:
    runs-on: [ self-hosted,aws-ec2-k8s-runner ]
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - uses: actions/checkout@v3
      - name: make build
        run: |
          make mod-vendor
          make lint
          make
  make-test-pr:
    runs-on: [ self-hosted,aws-ec2-k8s-runner ]
    if: ${{ github.event_name == 'pull_request' }}
    needs: [ make-build-pr ]
    steps:
      - uses: actions/checkout@v3
      - name: make test
        run: |
          make mod-vendor
          make test
  helm-test-pr:
    runs-on: [ self-hosted,aws-ec2-k8s-runner ]
    if: ${{ github.event_name == 'pull_request' }}
    needs: [ make-test-pr ]
    steps:
      - uses: actions/checkout@v3
      - name: helm test
        run: |
          make helm-test