name: ISSUE-VALID-PULL-REQUEST

on:
  pull_request:
#  pull_request_target:
#    types: [ edited, synchronize, opened, reopened ]

env:
  GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

jobs:
  issue-valid:
    name: Issue Valid
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: issue valid
        run: |
          bash ${{ github.workspace }}/.github/workflows/issue-valid.sh \
            ${{ github.repository }} \
            ${{ github.repository_owner }} \
            ${{ github.event.pull_request.number }}
      
