name: RELEASE-VERSION

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'The tag name of release'
        required: true
        default: ''

run-name: ref_name:${{ github.ref_name }} release_version:${{ inputs.release_version }}

env:
  RELEASE_BOT_WEBHOOK: ${{ secrets.RELEASE_BOT_WEBHOOK }}

jobs:
  release-version:
    runs-on: ubuntu-latest
    steps:
      - name: checkout branch ${{ github.ref_name }}
        uses: actions/checkout@v3

      - name: release message
        run: |
          bash .github/utils/utils.sh --type 11 \
            --tag-name "${{ inputs.release_version }}" \
            --bot-webhook ${{ env.RELEASE_BOT_WEBHOOK }}

      - name: push tag
        run: |
          git tag ${{ inputs.release_version }}
          git push origin ${{ inputs.release_version }}

  send-message:
    runs-on: ubuntu-latest
    needs: release-version
    if: ${{ failure() || cancelled() }}
    steps:
      - uses: actions/checkout@v3
      - name: release message
        run: |
          bash .github/utils/utils.sh --type 12 \
            --content "release\u00a0error" \
            --run-url "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID" \
            --bot-webhook ${{ env.RELEASE_BOT_WEBHOOK }}
