name: RELEASE-PUBILSH

on:
  release:
    types: [ released, prereleased ]

env:
  GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
  TAG_NAME: ${{ github.ref_name }}
  CLI_REPO: 'JashBook/hzs-test'

jobs:
  update-release:
    name: Update Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: update release ${{ env.CLI_NAME }} latest
        run: |
          echo "test"
#          bash ${{ github.workspace }}/.github/utils/utils.sh \
#            --type 4 \
#            --tag-name ${{ env.TAG_NAME }} \
#            --github-repo ${{ env.CLI_REPO }} \
#            --github-token ${{ env.GITHUB_TOKEN }}




#      - name: Build project
#        run: |
#          zip --junk-paths my-artifact README.md
#      - name: "get upload_url"
#        id: release
#        run: echo "::set-output name=upload_url::https://uploads.github.com/repos/$GITHUB_REPOSITORY/releases/$(jq --raw-output '.release.id' $GITHUB_EVENT_PATH)/assets{?name,label}"
#      - name: upload release asset
#        uses: actions/upload-release-asset@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
#        with:
#          upload_url: ${{ steps.release.outputs.upload_url }}
#          asset_path: ./my-artifact.zip
#          asset_name: my-artifact.zip
#          asset_content_type: application/zip