name: RELEASE-VERSION

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'The tag name of release'
        required: true
        default: ''


run-name: ${{ github.ref }}:${{ inputs.release_version }}


jobs:
  release-version:
    runs-on: ubuntu-latest
    steps:
      - name: checkout ${{ github.ref }}
        uses: actions/checkout@v3

      - name: push tag
        run: |
          git tag ${{ inputs.release_version }}
          git push origin ${{ inputs.release_version }}
