name: RELEASE-TAG

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'The tag name to trigger publish release'
        required: true
        default: ''
      branch_name:
        description: 'The tag name to trigger publish release'
        required: true
        default: ''

run-name: release_version:${{ inputs.release_version }}


jobs:
  release-version:
    runs-on: ubuntu-latest
    steps:
      - name: checkout ${{ inputs.branch_name }}
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.branch_name }}

      - name: push tag
        run: |
          git tag ${{ inputs.release_version }}
          git push origin ${{ inputs.release_version }}
