name: RELEASE-PUBILSH

on:
  release:
    types: [ published edited ]

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: echo release
        run:
          echo "${{ github.ref_name }}"
          echo "${{ github.event.release }}"
          echo "${{ github.event.release.prerelease }}"


#      - name: Build project
#        run: |
#          zip --junk-paths my-artifact README.md
#      - name: "get upload_url"
#        id: release
#        run: echo "::set-output name=upload_url::https://uploads.github.com/repos/$GITHUB_REPOSITORY/releases/$(jq --raw-output '.release.id' $GITHUB_EVENT_PATH)/assets{?name,label}"
#      - name: upload release asset
#        uses: actions/upload-release-asset@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
#        with:
#          upload_url: ${{ steps.release.outputs.upload_url }}
#          asset_path: ./my-artifact.zip
#          asset_name: my-artifact.zip
#          asset_content_type: application/zip