name: skopeo sync images

on:
  workflow_dispatch:

jobs:
  script:
    runs-on: ubuntu-latest
    steps:
      - name : skopeo sync images
        run: |
          skopeo sync -h
          bash ${{ github.workspace }}/.github/utils/skopeo_copy.sh \
            "${{ secrets.DOCKER_USER }}:${{ secrets.DOCKER_PASSWORD }}" \
            "${{ secrets.ALIYUN_USER }}:${{ secrets.ALIYUN_PASSWORD }}" \
            ${{ github.workspace }}/.github/utils/images-list.txt
