name: skopeo sync mysql

on:
  workflow_dispatch:

jobs:
  script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name : skopeo sync mysql
        run: |
          skopeo sync -h
          skopeo sync --all \
            --src-creds "${{ secrets.DOCKER_USER }}:${{ secrets.DOCKER_PASSWORD }}" \
            --dest-creds "${{ secrets.ALIYUN_USER }}:${{ secrets.ALIYUN_PASSWORD }}" \
            --src docker \
            --dest docker \
            docker.io/apecloud/apecloud-mysql-server \
            registry.cn-hangzhou.aliyuncs.com/apecloud
