name: TRIGGER-RELEASE

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'The tag name of release'
        required: true
        default: ''

run-name: request:${{ inputs.release_version }}

env:
  GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}


jobs:
  trigger-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: trigger release
        run: |
          echo ${{ inputs.release_version }}

    
